name: firebase_storage_dart
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  firebase_core_dart: ^1.0.1
  http: ^0.13.5
  mime: ^1.0.4
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
