name: firebase_storage_dart
description: A starting point for Dart libraries or applications.
version: 0.1.0-dev.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  firebase_auth_dart: ^0.1.1
  firebase_core_dart: ^0.1.1
  firebaseapis: ^0.1.1
dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
