name: firebase_app_installations_dart
description: Pure Dart implementation of FlutterFire Installations API
version: 1.0.0
repository: https://github.com/invertase/flutterfire_desktop

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  crypto: ^3.0.2
  firebase_core_dart: ^1.0.0
  firebaseapis: ^0.1.1
  googleapis_auth: ^1.1.0
  http: ^0.13.4
  meta: ^1.3.0
  storagebox: ^0.1.0+3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
