name: firebase_storage_desktop
description: A new Flutter plugin project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  firebase_core: ^2.4.1
  firebase_core_dart: ^1.0.1
  firebase_storage_dart: ^1.0.0
  firebase_storage_platform_interface: ^4.1.26
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    implements: firebase_storage
    platforms:
      # TODO when doing development on macOS, uncomment this.
      macos:
        dartPluginClass: FirebaseStorageDesktop
      linux:
        dartPluginClass: FirebaseStorageDesktop
      windows:
        dartPluginClass: FirebaseStorageDesktop
