name: firebase_remote_config_dart
description: Pure Dart implementation of FlutterFire RemoteConfig API.
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_desktop
version: 0.1.0-dev.0

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  firebase_core_dart: ^0.1.1
  firebaseapis: ^0.1.2
  googleapis_auth: ^1.3.1
  http: ^0.13.4
  meta: ^1.7.0
  storagebox: ^0.1.0+2

dev_dependencies:
  mockito: ^5.1.0
  test: ^1.16.0

