name: flutterfire_functions_dart
description: Pure Dart implementation of FlutterFire CloudFunctions API.
homepage: https://firebase.flutter.dev
repository: https://github.com/invertase/flutterfire_dart
version: 0.1.0-dev.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:  
  collection: ^1.15.0
  flutterfire_core_dart: any
  http: any
  meta: ^1.7.0

dev_dependencies: 

  test: ^1.16.0
  