name: all_packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Flutter'
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: 'Install Tools'
        run: ./.github/workflows/scripts/install-tools.sh
      - name: 'Analyze'
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Flutter'
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: 'Install Tools'
        run: ./.github/workflows/scripts/install-tools.sh
      - name: 'Dart'
        run: |
          melos run format
          ./.github/workflows/scripts/validate-formatting.sh

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Install Node.js 12
        with:
          node-version: "12"
      - name: 'Install Flutter'
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: 'Install Tools'
        run: |
          ./.github/workflows/scripts/install-tools.sh
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: 'Run Tests'
        run: melos run test --no-select

  test_windows:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Install Node.js 12
        with:
          node-version: "12"
      - name: 'Install Flutter'
        run: .\.github\workflows\scripts\install-flutter.bat stable
      - name: 'Install Tools'
        run: |
          .\.github\workflows\scripts\install-tools.bat
          npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd .\.github\workflows\scripts && .\start-firebase-emulator.bat
      - name: 'Run Tests'
        run: cmd /c melos run test --no-select
