name: all_packages
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Flutter'
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: 'Install Tools'
        run: ./.github/workflows/scripts/install-tools.sh
      - name: 'Analyze'
        uses: invertase/github-action-dart-analyzer@v1
        with:
          fatal-infos: true
          fatal-warnings: true

  format:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: 'Install Flutter'
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: 'Install Tools'
        run: ./.github/workflows/scripts/install-tools.sh
      - name: 'Dart'
        run: |
          melos run format
          ./.github/workflows/scripts/validate-formatting.sh

  test_linux:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Install Node.js 12
        with:
          node-version: '12'
      - name: 'Install Flutter'
        run: ./.github/workflows/scripts/install-flutter.sh stable
      - name: 'Install Tools'
        run: |
          ./.github/workflows/scripts/install-tools.sh
          sudo npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd ./.github/workflows/scripts && ./start-firebase-emulator.sh
      - name: 'Install Linux Dependencies'
        run: |
          sudo apt update
          sudo apt install -y cmake dbus libblkid-dev libgtk-3-dev liblzma-dev ninja-build pkg-config xvfb clang-format
          sudo apt install -y libwebkit2gtk-4.0-dev
      - name: 'Run Tests'
        working-directory: tests
        run: |
          flutter config --enable-linux-desktop
          flutter drive -d linux --no-pub --target=./test_driver/driver_e2e.dart --dart-define=CI=true

  test_windows:
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        name: Install Node.js 12
        with:
          node-version: '12'
      - name: 'Install Flutter'
        run: .\.github\workflows\scripts\install-flutter.bat stable
      - name: 'Install Tools'
        run: |
          .\.github\workflows\scripts\install-tools.bat
          npm i -g firebase-tools
      - name: Start Firebase Emulator
        run: cd .\.github\workflows\scripts && .\start-firebase-emulator.bat
      - name: 'Run Tests'
        working-directory: tests
        run: cmd /c flutter drive -d windows --no-pub --target=./test_driver/driver_e2e.dart
